### ISSUE TITLE
Bootloop Duo 2 

### ISSUE THREAD

**Issue by Mirilali** [WOA-Project/SurfaceDuo-Guides#36]
Now i did everything right and i installed the vNext (Zinc Semester) but now if i fastboot boot uefi.img windows load thanf the circle stop doing anything and it boot bacl into bootloader. 

Driver are installed correctly with the drivers (12 hrs. ago)

Last Issue from my side Please help

**Comment by Mirilali** [comment]
![Uploading 4DE2DF46-0601-4244-A7B8-DF61D1217DB4.jpeg…]()

**Comment by Mirilali** [comment]
![Uploading 26E75E47-558D-4CEE-813B-442CEDB7AC23.jpeg…]()

**Comment by Mirilali** [comment]
So it tries do boot windows, but then stop and it restarts to bootloader. Android it working fine

**Comment by gus33000** [comment]
Hi,

Surface Duo 2 is not a priority for us at the moment and is more of a proof of concept, such problems are to be expected, even if it goes further you would notice the experience isn't enjoyable at all and a lot remains broken.

Regardless, you may be able to get it to work provided:

- You follow our guides correctly
- You use the latest UEFI version and driver versions
- You use the latest Windows Insider Dev channel build (currently 25300)
- You may have to rename https://github.com/WOA-Project/SurfaceDuo-Drivers/blob/main/components/QC8350/Platform/PLATFORM.SOC_QC8350.BASE/Source/Drivers/USB/qcusbcucsi8350.inf to qcusbcucsi8350.inf_ before running driverupdater due to unknown issues

then maybe it will work.

But i will reemphasize this device is not currently the priority for us, nor we are actively working on it, priority remains on Duo 1 for the time being as Duo 2 has bigger challenges to tackle and that time isn't really available to focus on it too. So if it's broken, that's really expected at the moment and unfortunately there is not much we are going to be able to do for you here. It is however meant to boot up, it just will be a terrible experience and may be very broken (just like you just so), and very sluggish too, more than duo 1.

I'm going to close this issue now, I'll keep monitoring if you post any eventual comment but realistically will not be able to assist further due to the earliness of the port and the proof of concept nature of Surface Duo 2 Windows support now. I hope you understand.

-Gustave
