### ISSUE TITLE
Device hangs on uefi boot

### ISSUE THREAD

**Issue by bloodysniper3** [WOA-Project/SurfaceDuo-Guides#50]
after I updated Android, the duo 1 hangs on uefi during initial boot screen. I tried both uefi and same problem.

**Comment by gus33000** [comment]
Hello, What exact android version are you on? What exact version of the uefi are you using? What variant of the uefi are you using? Best if you could also specify the filename of the zip file you used for the uefi. What also are your Windows driver versions? Does it hang on the cat image or the surface white logo (4 squares)?

**Comment by bloodysniper3** [comment]
im on android 12 2022.827.21. using uefi Version 2305.64  SM8150.UEFI.Surface.Duo.1.Secure.Boot.Disabled and SM8150.UEFI.Surface.Duo.1. I downloaded windows driver Umbreon . it just hangs on the cat image

**Comment by bloodysniper3** [comment]
This all that comes up

![20230526_090400](https://github.com/WOA-Project/SurfaceDuo-Guides/assets/98128406/3be4211d-c8af-45a4-b2c2-4840d13f3ea7)

**Comment by gus33000** [comment]
Maybe you have a file system corruption on the esp partition for windows that android would have caused randomly. You should try the following:

Using any of the guides, boot into twrp and go to mass storage following the "msc.sh" section of a guide. Only follow this part here however.

Once done you should be in mass storage. From this point, follow the guide section that instructs you to assign a drive letter to the esp partition (the partition in diskpart will be labelled "System" instead of "Primary" or "Unknown")

From here you will have a drive letter assigned to it, for simplicity here I will assume you used B: but it can be anything you want once again.

Open a command prompt as administrator, (cmd.exe not pwsh). Navigate through the esp partition with "B:"

proceed with the following:

rmdir /q /s EFI

then refollow the section of the guide and only this one that contains "bcdboot" command(s)

try to boot the device into windows again and let us know if the device boots fine.

**Comment by bloodysniper3** [comment]
Sorry stuck at 'navigate through the esp partition with "b:". I assign mines "y", how do you switch to that drive in cmd.

**Comment by bloodysniper3** [comment]
No luck. I might try reinstalling windows again to see if that works

**Comment by bloodysniper3** [comment]
Update: I believe your first answer was correct, I notice my commands for esp drive wasn't working because I didnt notice the letter y: was already taken and it never mounted so changed it to another letter. I use the same commend an now its working. Thank you for your time and patience!

**Comment by gus33000** [comment]
Pinned this issue in case someone else gets the same problem, i've seen some people get this before, it's rare but happens enough to be worthy of a pin. Glad to see it's resolved!
